SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `FINAL_STANDING`;
DROP TABLE IF EXISTS `GAME`;
DROP TABLE IF EXISTS `GROUPS`;
DROP TABLE IF EXISTS `PLAYER`;
DROP TABLE IF EXISTS `PARTICIPANT`;
DROP TABLE IF EXISTS `PLAY_OFF_GAME`;
DROP TABLE IF EXISTS `SEASON`;
DROP TABLE IF EXISTS `TOURNAMENT`;
DROP TABLE IF EXISTS `USER`;
SET FOREIGN_KEY_CHECKS=1;

--
-- Database: `tournament_system`
--

-- --------------------------------------------------------

--
-- Table structure for table `FINAL_STANDING`
--

CREATE TABLE IF NOT EXISTS `FINAL_STANDING` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PLAYER_ID` int(11) DEFAULT NULL,
  `FINAL_RANK` int(11) NOT NULL,
  `TOURNAMENT_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `FINAL_RANK` (`FINAL_RANK`,`TOURNAMENT_ID`),
  KEY `TOURNAMENT_ID` (`TOURNAMENT_ID`),
  KEY `PLAYER_ID` (`PLAYER_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10 ;

-- --------------------------------------------------------

--
-- Table structure for table `GAME`
--

CREATE TABLE IF NOT EXISTS `GAME` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `HOME_PARTICIPANT_ID` int(11) NOT NULL,
  `AWAY_PARTICIPANT_ID` int(11) NOT NULL,
  `HOME_SCORE` int(4) DEFAULT NULL,
  `AWAY_SCORE` int(4) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `HOME_PARTICIPANT_ID` (`HOME_PARTICIPANT_ID`),
  KEY `AWAY_PARTICIPANT_ID` (`AWAY_PARTICIPANT_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10 ;

-- --------------------------------------------------------

--
-- Table structure for table `GROUPS`
--

CREATE TABLE IF NOT EXISTS `GROUPS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `NUMBER_OF_HOCKEY` int(4) NOT NULL DEFAULT '1',
  `TYPE` enum('B','F','P') NOT NULL DEFAULT 'B',
  `INDEX_OF_FIRST_HOCKEY` int(4) NOT NULL DEFAULT '1',
  `TOURNAMENT_ID` int(11) NOT NULL,
  `COPY_RESULT` tinyint(1) NOT NULL,
  `PLAY_THIRD_PLACE` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NAME` (`NAME`,`TOURNAMENT_ID`),
  KEY `TOURNAMENT_ID` (`TOURNAMENT_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10 ;

-- --------------------------------------------------------

--
-- Table structure for table `PARTICIPANT`
--

CREATE TABLE IF NOT EXISTS `PARTICIPANT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `POINTS` int(4) NOT NULL DEFAULT '0',
  `RANK` int(4) DEFAULT NULL,
  `GROUP_ID` int(11) NOT NULL,
  `PLAYER_ID` int(11) NOT NULL,
  `SCORE` varchar(10) NOT NULL DEFAULT '0:0',
  `EQUAL_RANK` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `PLAYER_ID` (`PLAYER_ID`),
  KEY `GROUP_ID` (`GROUP_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10 ;

-- --------------------------------------------------------

--
-- Table structure for table `PLAYER`
--

CREATE TABLE IF NOT EXISTS `PLAYER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `SURNAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `CLUB` varchar(255) DEFAULT NULL,
  `PLAYER_DISCRIMINATOR` varchar(3) NOT NULL DEFAULT '',
  `WORLD_RANKING` int(11) DEFAULT NULL,
  `USER_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NAME` (`NAME`,`SURNAME`,`PLAYER_DISCRIMINATOR`),
  KEY `USER_ID` (`USER_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10 ;

-- --------------------------------------------------------

--
-- Table structure for table `PLAY_OFF_GAME`
--

CREATE TABLE IF NOT EXISTS `PLAY_OFF_GAME` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `HOME_PARTICIPANT_ID` int(11) DEFAULT NULL,
  `AWAY_PARTICIPANT_ID` int(11) DEFAULT NULL,
  `GROUP_ID` int(11) NOT NULL,
  `POSITION` int(4) NOT NULL,
  `RESULTS` varchar(100) DEFAULT NULL,
  `WINNER` enum('HOME','AWAY') DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `GROUP_ID` (`GROUP_ID`),
  KEY `AWAY_PARTICIPANT_ID` (`AWAY_PARTICIPANT_ID`),
  KEY `HOME_PARTICIPANT_ID` (`HOME_PARTICIPANT_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10 ;

-- --------------------------------------------------------

--
-- Table structure for table `SEASON`
--

CREATE TABLE IF NOT EXISTS `SEASON` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `USER_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `USER_ID` (`USER_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10 ;

-- --------------------------------------------------------

--
-- Table structure for table `TOURNAMENT`
--

CREATE TABLE IF NOT EXISTS `TOURNAMENT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `SEASON_ID` int(11) NOT NULL,
  `FINAL_PROMOTING` int(4) NOT NULL DEFAULT '6',
  `LOWER_PROMOTING` int(4) NOT NULL DEFAULT '5',
  `WIN_POINTS` int(1) NOT NULL DEFAULT '2',
  `PLAY_OFF_A` int(4) NOT NULL DEFAULT '16',
  `PLAY_OFF_LOWER` int(4) NOT NULL DEFAULT '8',
  `MIN_PLAYERS_IN_GROUP` int(11) NOT NULL DEFAULT '4',
  PRIMARY KEY (`ID`),
  KEY `SEASON_ID` (`SEASON_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10 ;

-- --------------------------------------------------------

--
-- Table structure for table `USER`
--

CREATE TABLE IF NOT EXISTS `USER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL,
  `SURNAME` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(255) NOT NULL,
  `USER_NAME` varchar(255) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `ROLE` enum('ADMIN','USER') DEFAULT NULL,
  `PLATNOST` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USER_NAME` (`USER_NAME`),
  UNIQUE KEY `EMAIL` (`EMAIL`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10 ;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `FINAL_STANDING`
--
ALTER TABLE `FINAL_STANDING`
  ADD CONSTRAINT `FINAL_STANDING_ibfk_1` FOREIGN KEY (`TOURNAMENT_ID`) REFERENCES `TOURNAMENT` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `FINAL_STANDING_ibfk_2` FOREIGN KEY (`PLAYER_ID`) REFERENCES `PLAYER` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `GAME`
--
ALTER TABLE `GAME`
  ADD CONSTRAINT `GAME_ibfk_1` FOREIGN KEY (`HOME_PARTICIPANT_ID`) REFERENCES `PARTICIPANT` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `GAME_ibfk_2` FOREIGN KEY (`AWAY_PARTICIPANT_ID`) REFERENCES `PARTICIPANT` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `GROUPS`
--
ALTER TABLE `GROUPS`
  ADD CONSTRAINT `GROUPS_ibfk_1` FOREIGN KEY (`TOURNAMENT_ID`) REFERENCES `TOURNAMENT` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `PARTICIPANT`
--
ALTER TABLE `PARTICIPANT`
  ADD CONSTRAINT `PARTICIPANT_ibfk_1` FOREIGN KEY (`GROUP_ID`) REFERENCES `GROUPS` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `PARTICIPANT_ibfk_2` FOREIGN KEY (`PLAYER_ID`) REFERENCES `PLAYER` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `PLAYER`
--
ALTER TABLE `PLAYER`
  ADD CONSTRAINT `PLAYER_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `PLAY_OFF_GAME`
--
ALTER TABLE `PLAY_OFF_GAME`
  ADD CONSTRAINT `PLAY_OFF_GAME_ibfk_1` FOREIGN KEY (`HOME_PARTICIPANT_ID`) REFERENCES `PARTICIPANT` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `PLAY_OFF_GAME_ibfk_2` FOREIGN KEY (`AWAY_PARTICIPANT_ID`) REFERENCES `PARTICIPANT` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `PLAY_OFF_GAME_ibfk_3` FOREIGN KEY (`GROUP_ID`) REFERENCES `GROUPS` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `SEASON`
--
ALTER TABLE `SEASON`
  ADD CONSTRAINT `SEASON_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `TOURNAMENT`
--
ALTER TABLE `TOURNAMENT`
  ADD CONSTRAINT `TOURNAMENT_ibfk_1` FOREIGN KEY (`SEASON_ID`) REFERENCES `SEASON` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
