-- Database: `tournament_system`
--

-- --------------------------------------------------------

--
-- Table structure for table `GAME`
--

CREATE TABLE IF NOT EXISTS `GAME` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `HOME_PLAYER_RESULT_ID` int(11) NOT NULL,
  `AWAY_PLAYER_RESULT_ID` int(11) NOT NULL,
  `HOME_SCORE` int(4) DEFAULT NULL,
  `AWAY_SCORE` int(4) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `HOME_PLAYER_RESULT_ID` (`HOME_PLAYER_RESULT_ID`),
  KEY `AWAY_PLAYER_RESULT_ID` (`AWAY_PLAYER_RESULT_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;

-- --------------------------------------------------------

--
-- Table structure for table `GROUPS`
--

CREATE TABLE IF NOT EXISTS `GROUPS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `NUMBER_OF_HOCKEY` int(4) NOT NULL DEFAULT '1',
  `GROUP_TYPE` enum('B','F','P') NOT NULL DEFAULT 'B',
  `INDEX_OF_FIRST_HOCKEY` int(4) NOT NULL DEFAULT '1',
  `TOURNAMENT_ID` int(11) NOT NULL,
  `COPY_RESULT` tinyint(1) NOT NULL,
  `PLAY_THIRD_PLACE` tinyint(1) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NAME` (`NAME`,`TOURNAMENT_ID`),
  KEY `TOURNAMENT_ID` (`TOURNAMENT_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;

-- --------------------------------------------------------

--
-- Table structure for table `PLAYER`
--

CREATE TABLE IF NOT EXISTS `PLAYER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `SURNAME` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `CLUB` varchar(255) DEFAULT NULL,
  `USER_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `USER_ID` (`USER_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;

-- --------------------------------------------------------

--
-- Table structure for table `PLAYER_RESULT`
--

CREATE TABLE IF NOT EXISTS `PLAYER_RESULT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `POINTS` int(4) NOT NULL DEFAULT '0',
  `RANK` int(4) DEFAULT NULL,
  `GROUP_ID` int(11) NOT NULL,
  `PLAYER_ID` int(11) NOT NULL,
  `SCORE` varchar(10) NOT NULL DEFAULT '0:0',
  `EQUAL_RANK` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `PLAYER_ID` (`PLAYER_ID`),
  KEY `GROUP_ID` (`GROUP_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;

-- --------------------------------------------------------

--
-- Table structure for table `PLAY_OFF_GAME`
--

CREATE TABLE IF NOT EXISTS `PLAY_OFF_GAME` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `HOME_PLAYER_ID` int(11) DEFAULT NULL,
  `AWAY_PLAYER_ID` int(11) DEFAULT NULL,
  `GROUP_ID` int(11) NOT NULL,
  `POSITION` int(4) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `HOME_PLAYER_ID` (`HOME_PLAYER_ID`),
  KEY `AWAY_PLAYER_ID` (`AWAY_PLAYER_ID`),
  KEY `POSITION` (`POSITION`),
  KEY `GROUP_ID` (`GROUP_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;

-- --------------------------------------------------------

--
-- Table structure for table `PLAY_OFF_RESULT`
--

CREATE TABLE IF NOT EXISTS `PLAY_OFF_RESULT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `HOME_SCORE` int(11) DEFAULT NULL,
  `AWAY_SCORE` int(11) DEFAULT NULL,
  `OVERTIME` tinyint(1) NOT NULL,
  `PLAY_OFF_GAME_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `PLAY_OFF_GAME_ID` (`PLAY_OFF_GAME_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;

-- --------------------------------------------------------

--
-- Table structure for table `SEASON`
--

CREATE TABLE IF NOT EXISTS `SEASON` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `USER_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `USER_ID` (`USER_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;

-- --------------------------------------------------------

--
-- Table structure for table `TOURNAMENT`
--

CREATE TABLE IF NOT EXISTS `TOURNAMENT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `SEASON_ID` int(11) NOT NULL,
  `FINAL_PROMOTING` int(4) NOT NULL DEFAULT '6',
  `LOWER_PROMOTING` int(4) NOT NULL DEFAULT '5',
  `WIN_POINTS` int(1) NOT NULL DEFAULT '2',
  `PLAY_OFF_A` int(4) NOT NULL DEFAULT '16',
  `PLAY_OFF_LOWER` int(4) NOT NULL DEFAULT '8',
  `MIN_PLAYERS_IN_GROUP` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `SEASON_ID` (`SEASON_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;

-- --------------------------------------------------------

--
-- Table structure for table `USER`
--

CREATE TABLE IF NOT EXISTS `USER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `SURNAME` varchar(255) NOT NULL,
  `EMAIL` varchar(255) NOT NULL,
  `USER_NAME` varchar(255) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `ROLE` varchar(255) DEFAULT NULL,
  `PLATNOST` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USER_NAME` (`USER_NAME`),
  UNIQUE KEY `EMAIL` (`EMAIL`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `GAME`
--
ALTER TABLE `GAME`
  ADD CONSTRAINT `GAME_ibfk_1` FOREIGN KEY (`HOME_PLAYER_RESULT_ID`) REFERENCES `PLAYER_RESULT` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `GAME_ibfk_2` FOREIGN KEY (`AWAY_PLAYER_RESULT_ID`) REFERENCES `PLAYER_RESULT` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `GROUPS`
--
ALTER TABLE `GROUPS`
  ADD CONSTRAINT `GROUPS_ibfk_1` FOREIGN KEY (`TOURNAMENT_ID`) REFERENCES `TOURNAMENT` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `PLAYER`
--
ALTER TABLE `PLAYER`
  ADD CONSTRAINT `PLAYER_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `PLAYER_RESULT`
--
ALTER TABLE `PLAYER_RESULT`
  ADD CONSTRAINT `PLAYER_RESULT_ibfk_1` FOREIGN KEY (`GROUP_ID`) REFERENCES `GROUPS` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `PLAYER_RESULT_ibfk_2` FOREIGN KEY (`PLAYER_ID`) REFERENCES `PLAYER` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `PLAY_OFF_GAME`
--
ALTER TABLE `PLAY_OFF_GAME`
  ADD CONSTRAINT `PLAY_OFF_GAME_ibfk_1` FOREIGN KEY (`HOME_PLAYER_ID`) REFERENCES `PLAYER` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `PLAY_OFF_GAME_ibfk_4` FOREIGN KEY (`AWAY_PLAYER_ID`) REFERENCES `PLAYER` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `PLAY_OFF_GAME_ibfk_5` FOREIGN KEY (`GROUP_ID`) REFERENCES `GROUPS` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `PLAY_OFF_RESULT`
--
ALTER TABLE `PLAY_OFF_RESULT`
  ADD CONSTRAINT `PLAY_OFF_RESULT_ibfk_1` FOREIGN KEY (`PLAY_OFF_GAME_ID`) REFERENCES `PLAY_OFF_GAME` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `SEASON`
--
ALTER TABLE `SEASON`
  ADD CONSTRAINT `SEASON_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `TOURNAMENT`
--
ALTER TABLE `TOURNAMENT`
  ADD CONSTRAINT `TOURNAMENT_ibfk_1` FOREIGN KEY (`SEASON_ID`) REFERENCES `SEASON` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- user with password test  
INSERT INTO `USER` (`ID`, `NAME`, `SURNAME`, `EMAIL`, `USER_NAME`, `PASSWORD`, `ROLE`, `PLATNOST`) VALUES
(1, 'Tomas', 'Hudec', 'hudi1@gmail.com', 'hudi1', 'ee26b0dd4af7e749aa1a8ee3c10ae9923f618980772e473f8819a5d4940e0db27ac185f8a0e1d5f84f88bc887fd67b143732c304cc5fa9ad8e6f57f50028a8ff', 'ADMIN', 0);  

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;